export const ar = {
  // login and signup pages:
  login: "تسجيل الدخول",
  email: "البريد الإلكتروني",
  username: "اسم المستخدم",
  password: "كلمة المرور",
  please_enter_username_and_password: "يرجى إدخال اسم المستخدم وكلمة المرور",
  invalid_credentials: "اسم المستخدم أو كلمة المرور غير صحيحة",
  account_disabled: "تم تعطيل الحساب",

  home: "الرئيسية",
  visits: "الزيارات",
  payments: "المدفوعات",
  settings: "الإعدادات",
  add_patient: "إضافة مريض",
  add_visit: "إضافة زيارة",
  search_patient: "البحث عن مريض",
  notes: "ملاحظات",
  confirm_visit: "تأكيد الزيارة",
  select_another_patient: "اختيار مريض آخر",

  // Dashboard page:
  today_visits: "زيارات اليوم",
  new_patients: "مرضى جدد",
  completed_visits: "الزيارات المكتملة",
  persons: "أشخاص",
  monthly_visits: "الزيارات الشهرية",
  today_payments: "مدفوعات اليوم",
  total_month_payments: "مدفوعات الشهر",

  // Visits page:
  amount: "المبلغ",
  completed: "مكتمل",
  pending: "قيد الانتظار",
  edit_price: "تعديل السعر",
  pick_date: "اختر التاريخ",
  visit_date: "تاريخ الزيارة",
  created_at: "تاريخ الإنشاء",
  no_visits: "لا توجد زيارات",
  dentist_price_required: "يجب على طبيب الأسنان تحديد السعر قبل التأكيد.",
  visit_details: "تفاصيل الزيارة",
  number_of_visits: "عدد الزيارات",
  visit_notes: "وصف العلاج",
  create_patient: "إنشاء مريض",
  add_new_patient: "إضافة مريض جديد",

  // payments page:
  no_payments: "لا توجد مدفوعات",
  patient: "المريض",
  created_by: "تم الإنشاء بواسطة",
  price_not_set: "يجب على طبيب الأسنان تحديد السعر قبل التأكيد.",
  worker: "الموظف",
  processed_at: "تاريخ الدفع",
  payment_details: "تفاصيل الدفع",

  // patients data:
  first_name: "الاسم",
  last_name: "اللقب",
  sex: "الجنس",
  male: " ذكر",
  female: " أنثى",
  age: "العمر",
  phone: "الهاتف",
  edit_patient: "تعديل المريض",
  delete_patient: "حذف المريض",
  personal_details: "التفاصيل الشخصية",
  financial_payments: "المدفوعات المالية",
  total_paid: "إجمالي المدفوعات",
  total_pending: "إجمالي المبالغ المعلقة",
  patient_visits: "زيارات المريض",
  no_patient_visits: "لا توجد زيارات لهذا المريض",
  patient_profile: "ملف المريض",

  // settings page:
  language: "اللغة",
  dark_theme: "الوضع الليلي",
  notifications: "الإشعارات",
  version: "الإصدار",
  workers_management: "إدارة العمال",
  logout: "تسجيل الخروج",
  patients: "المرضى",

  // workers page:
  add_new_worker: "إضافة عامل جديد",
  edit_worker: "تعديل العامل",
  full_name: "الاسم الكامل",
  create_worker: "إنشاء عامل",
  creating: "جارٍ الإنشاء...",
  workers_list: "قائمة العمال",
  active: "نشط",
  disabled: "معطّل",
  pause: "إيقاف",
  activate: "تفعيل",
  update_worker: "تحديث العامل",
  edit_credentials: "تعديل بيانات الدخول",
  update: "تحديث",
  updating: "جارٍ التحديث...",
  username_required: "اسم المستخدم مطلوب",
  password_required: "كلمة المرور مطلوبة",
  full_name_required: "الاسم الكامل مطلوب",
  worker_added: "تم إضافة العامل",
  worker_updated: "تم تحديث بيانات العامل",
  please_fill_all_fields: "يرجى ملء جميع الحقول",

  // utilities and general use:
  cancel: "إلغاء",
  save: "حفظ",
  close: "إغلاق",
  confirm: "تأكيد",

  // Notifications
  new_visit: "زيارة جديدة",
  new_visit_body: "تم إضافة زيارة مريض جديدة.",
  payment_confirmed: "تم تأكيد الدفع",
  payment_confirmed_body: "تم تأكيد دفع مبلغ {amount} دج.",
  new_patient: "تم إضافة مريض جديد",
  new_patient_body: "تم إضافة مريض جديد باسم {name}.",
  visit_completed: "اكتملت الزيارة",
  visit_completed_body: "للمريض مبلغ للدفع. يرجى التأكيد.",
} as const;
