export const en = {
  // login and signup pages
  login: "Login",
  email: "Email",
  username: "Username",
  password: "Password",
  please_enter_username_and_password:
    "Please enter your user name and password",
  invalid_credentials: "Invalid user name or password",
  account_disabled: "Account is disabled",

  // Dashboard / main pages
  home: "Home",
  visits: "Visits",
  payments: "Payments",
  settings: "Settings",
  add_patient: "Add Patient",
  add_visit: "Add Visit",
  search_patient: "Search Patient",
  notes: "Notes",
  confirm_visit: "Confirm Visit",
  select_another_patient: "Select Another Patient",

  // Dashboard page metrics
  today_visits: "Today's Visits",
  new_patients: "New Patients",
  completed_visits: "Completed Visits",
  persons: "Persons",
  monthly_visits: "Monthly Visits",
  today_payments: "Today's Payments",
  total_month_payments: "Total Month Payments",
  today_payments_completed: "Today Payments Completed",
  of_total: "{completed} of {total}",
  increase_from_last_month: "↑ {percent}% from last month",
  since_8_am: "Since 8 AM",

  // Visits page
  amount: "Amount",
  completed: "Completed",
  pending: "Pending",
  edit_price: "Edit Price",
  pick_date: "Pick Date",
  visit_date: "Visit Date",
  created_at: "Created at",
  no_visits_for: "No visits for",
  dentist_price_required: "Dentist must set the price before confirming.",
  visit_details: "Visit Details",
  number_of_visits: "Number of Visits",
  visit_notes: "Visit Notes",

  // Payments page
  no_payments_for: "No payments for",
  patient: "Patient",
  created_by: "Created by",
  price_not_set: "Dentist must set the price before confirming.",
  worker: "Worker",
  processed_at: "Processed At",
  payment_details: "Payment Details",

  // Patients data
  first_name: "First Name",
  last_name: "Last Name",
  sex: "Sex",
  male: " Male",
  female: " Female",
  age: "Age",
  phone: "Phone",
  edit_patient: "Edit Patient",
  delete_patient: "Delete Patient",
  personal_details: "Personal Details",
  financial_payments: "Financial Payments",
  total_paid: "Total Paid",
  total_pending: "Total Pending",
  patient_visits: "Patient Visits",
  no_patient_visits: "No visits for this patient",
  patient_profile: "Patient Profile",

  // Settings page
  language: "Language",
  dark_theme: "Dark Theme",
  notifications: "Notifications",
  version: "Version",
  workers_management: "Workers Management",
  logout: "Logout",

  // Workers page
  add_new_worker: "Add New Worker",
  edit_worker: "Edit Worker",
  full_name: "Full Name",
  create_worker: "Create Worker",
  creating: "Creating...",
  workers_list: "Workers List",
  active: "Active",
  disabled: "Disabled",
  pause: "Pause",
  activate: "Activate",
  update_worker: "Update Worker",
  edit_credentials: "Edit Credentials",
  update: "Update",
  updating: "Updating...",
  username_required: "Username is required",
  password_required: "Password is required",
  full_name_required: "Full name is required",
  worker_added: "Worker added",
  worker_updated: "Worker updated",
  please_fill_all_fields: "Please fill all fields",

  // Utilities and common actions
  cancel: "Cancel",
  save: "Save",
  close: "Close",
  confirm: "Confirm",

  // Notifications
  new_visit: "New Visit",
  new_visit_body: "A new patient visit was added.",
  payment_confirmed: "Payment Confirmed",
  payment_confirmed_body: "A payment of {amount} DA was confirmed.",
  new_patient: "New Patient Added",
  new_patient_body: "A new patient named {name} was added.",
  visit_completed: "Visit Completed",
  visit_completed_body: "Patient has a price to pay. Please confirm it.",
} as const;
