export const fr = {
  // login and signup pages
  login: "Connexion",
  email: "Email",
  username: "Nom d'utilisateur",
  password: "Mot de passe",
  please_enter_username_and_password:
    "Veuillez entrer votre nom d'utilisateur et votre mot de passe",
  invalid_credentials: "Nom d'utilisateur ou mot de passe invalide",
  account_disabled: "Le compte est désactivé",

  // Dashboard / main pages
  home: "Accueil",
  visits: "Visites",
  payments: "Paiements",
  settings: "Paramètres",
  add_patient: "Ajouter un patient",
  add_visit: "Ajouter une visite",
  search_patient: "Rechercher un patient",
  notes: "Notes",
  confirm_visit: "Confirmer la visite",
  select_another_patient: "Sélectionner un autre patient",

  // Dashboard page metrics
  today_visits: "Visites d'aujourd'hui",
  new_patients: "Nouveaux patients",
  completed_visits: "Visites terminées",
  persons: "Personnes",
  monthly_visits: "Visites mensuelles",
  today_payments: "Paiements d'aujourd'hui",
  total_month_payments: "Paiements du mois",
  today_payments_completed: "Paiements terminés aujourd'hui",
  of_total: "{completed} sur {total}",
  increase_from_last_month: "↑ {percent}% par rapport au mois dernier",
  since_8_am: "Depuis 8h",

  // Visits page
  amount: "Montant",
  completed: "Terminé",
  pending: "En attente",
  edit_price: "Modifier le prix",
  pick_date: "Choisir la date",
  visit_date: "Date de la visite",
  created_at: "Créé le",
  no_visits: "Aucune visite",
  dentist_price_required: "Le dentiste doit fixer le prix avant de confirmer.",
  visit_details: "Détails de la visite",
  number_of_visits: "Nombre de visites",
  visit_notes: "Notes de la visite",

  // Payments page
  no_payments: "Aucun paiement",
  patient: "Patient",
  created_by: "Créé par",
  price_not_set: "Le dentiste doit fixer le prix avant de confirmer.",
  worker: "Travailleur",
  processed_at: "Traité le",
  payment_details: "Détails du paiement",

  // Patients data
  first_name: "Prénom",
  last_name: "Nom",
  sex: "Sexe",
  male: " Masculin",
  female: " Féminin",
  age: "Âge",
  phone: "Téléphone",
  edit_patient: "Modifier le patient",
  delete_patient: "Supprimer le patient",
  personal_details: "Détails personnels",
  financial_payments: "Paiements financiers",
  total_paid: "Total payé",
  total_pending: "Total en attente",
  patient_visits: "Visites du patient",
  no_patient_visits: "Aucune visite pour ce patient",
  patient_profile: "Profil du patient",

  // Settings page
  language: "Langue",
  dark_theme: "Thème sombre",
  notifications: "Notifications",
  version: "Version",
  workers_management: "Gestion des employés",
  logout: "Déconnexion",

  // Workers page
  add_new_worker: "Ajouter un nouvel employé",
  edit_worker: "Modifier l'employé",
  full_name: "Nom complet",
  create_worker: "Créer un employé",
  creating: "Création...",
  workers_list: "Liste des employés",
  active: "Actif",
  disabled: "Désactivé",
  pause: "Mettre en pause",
  activate: "Activer",
  update_worker: "Mettre à jour l'employé",
  edit_credentials: "Modifier les identifiants",
  update: "Mettre à jour",
  updating: "Mise à jour...",
  username_required: "Le nom d'utilisateur est requis",
  password_required: "Le mot de passe est requis",
  full_name_required: "Le nom complet est requis",
  worker_added: "Employé ajouté",
  worker_updated: "Employé mis à jour",
  please_fill_all_fields: "Veuillez remplir tous les champs",

  // Utilities and common actions
  cancel: "Annuler",
  save: "Enregistrer",
  close: "Fermer",
  confirm: "Confirmer",

  // Notifications
  new_visit: "Nouvelle Visite",
  new_visit_body: "Une nouvelle visite patient a été ajoutée.",
  payment_confirmed: "Paiement Confirmé",
  payment_confirmed_body: "Un paiement de {amount} DA a été confirmé.",
  new_patient: "Nouveau Patient Ajouté",
  new_patient_body: "Un nouveau patient nommé {name} a été ajouté.",
  visit_completed: "Visite Terminée",
  visit_completed_body:
    "Le patient a un montant à payer. Veuillez le confirmer.",
} as const;
