const { createClient } = require("@supabase/supabase-js");

const url = process.env.EXPO_PUBLIC_SUPABASE_URL;
const key = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY;

if (!url || !key) {
  throw new Error("Missing EXPO_PUBLIC_SUPABASE_URL or EXPO_PUBLIC_SUPABASE_ANON_KEY");
}

const now = Date.now();
const uniqueTag = `qa-consult-${now}`;
const doctorEmail = "test1@gmail.com";
const doctorPassword = "test1";

const results = [];

function add(name, ok, details = {}) {
  results.push({ name, ok, ...details });
}

function shortError(error) {
  return error?.message || String(error);
}

function expect(condition, message, details = {}) {
  if (!condition) {
    const error = new Error(message);
    error.details = details;
    throw error;
  }
}

async function login(email, password) {
  const client = createClient(url, key);
  const { data, error } = await client.auth.signInWithPassword({ email, password });
  if (error) throw error;
  return { client, session: data.session, user: data.user };
}

async function rpc(client, name, params) {
  const { data, error } = await client.rpc(name, params || {});
  if (error) throw error;
  return data;
}

function toArray(value) {
  return Array.isArray(value) ? value : [];
}

function hasAllValues(source, expected) {
  const haystack = new Set(toArray(source).map((item) => String(item)));
  return expected.every((item) => haystack.has(String(item)));
}

async function main() {
  let doctor;
  let patientId = null;
  let appointmentId = null;
  let consultationId = null;
  let prescriptionId = null;

  try {
    doctor = await login(doctorEmail, doctorPassword);
    add("doctor_login", true, { userId: doctor.user.id });
  } catch (error) {
    add("doctor_login", false, { error: shortError(error) });
    console.log(JSON.stringify(results, null, 2));
    return;
  }

  const client = doctor.client;
  const requesterId = doctor.user.id;

  try {
    patientId = await rpc(client, "rpc_create_patient", {
      p_created_by: requesterId,
      p_first_name: "QA",
      p_last_name: `Consult ${uniqueTag}`,
      p_date_of_birth: "1991-06-15",
      p_place_of_birth: "Blida",
      p_sex: "female",
      p_marital_status: "single",
      p_phone: `0557${String(now).slice(-6)}`,
      p_email: `${uniqueTag}@example.test`,
      p_address_street: "12 Test Avenue",
      p_address_city: "Blida",
      p_address_state: "Blida",
      p_blood_type: "A+",
      p_allergies: ["pollen"],
      p_chronic_diseases: ["asthma"],
      p_medications: ["none"],
      p_disabilities: null,
      p_height: 168,
      p_weight: 63,
    });
    add("patient_create", !!patientId, { patientId });
  } catch (error) {
    add("patient_create", false, { error: shortError(error) });
    console.log(JSON.stringify(results, null, 2));
    return;
  }

  try {
    appointmentId = await rpc(client, "rpc_create_appointment", {
      p_requester_id: requesterId,
      p_patient_id: patientId,
      p_doctor_id: requesterId,
      p_scheduled_at: new Date(now + 60 * 60 * 1000).toISOString(),
      p_status: "pending",
      p_type: "consultation",
      p_notes: `Consultation submodule QA ${uniqueTag}`,
    });
    add("appointment_create", !!appointmentId, { appointmentId });
  } catch (error) {
    add("appointment_create", false, { error: shortError(error) });
    console.log(JSON.stringify(results, null, 2));
    return;
  }

  try {
    const session = await rpc(client, "rpc_open_consultation", {
      p_requester_id: requesterId,
      p_appointment_id: appointmentId,
    });
    consultationId = session?.consultation?.id || null;
    expect(!!consultationId, "Consultation was not opened");
    add("consultation_open", true, {
      consultationId,
      consultationStatus: session?.consultation?.status ?? null,
    });
  } catch (error) {
    add("consultation_open", false, { error: shortError(error) });
    console.log(JSON.stringify(results, null, 2));
    return;
  }

  const observationsText = `Observation ${uniqueTag}`;
  const treatmentPlan = "Hydration, rest, and symptom monitoring";
  const followUp = "Review in 7 days";
  const selectedSymptoms = ["fatigue", "cephalee", "toux"];
  const diagnosisLabels = ["Sinusite", "Etat grippal"];
  const specialityPayload = {
    motif_consultation: "Headache and fatigue",
    glycemie: "1.01",
    hba1c: "5.8",
    examen_clinique: "ENT tenderness and mild fever",
    conclusion: `Stable after review ${uniqueTag}`,
    blood_pressure: "12/7",
    systolic_bp: 12,
    diastolic_bp: 7,
    weight_kg: 63,
    height_cm: 168,
    temperature_c: 37.4,
    symptoms_selected: selectedSymptoms,
    symptoms_summary: selectedSymptoms.join(", "),
    doctor_note: `Generated by ${uniqueTag}`,
  };

  try {
    const saved = await rpc(client, "rpc_save_consultation", {
      p_requester_id: requesterId,
      p_consultation_id: consultationId,
      p_observations: observationsText,
      p_treatment_plan: treatmentPlan,
      p_follow_up: followUp,
      p_status: "open",
      p_vitals: {
        weight: 63,
        height: 168,
        temperature: 37.4,
        systolic_bp: 12,
        diastolic_bp: 7,
      },
      p_parameters: {
        motif_consultation: specialityPayload.motif_consultation,
        glycemie: specialityPayload.glycemie,
        hba1c: specialityPayload.hba1c,
        examen_clinique: specialityPayload.examen_clinique,
        conclusion: specialityPayload.conclusion,
      },
      p_diagnoses: diagnosisLabels.map((label) => ({
        code: label,
        label,
      })),
      p_speciality_key: "general_medicine",
      p_speciality_payload: specialityPayload,
    });
    expect(saved === true, "Consultation save did not return true", { saved });
    add("consultation_save", true, { saved });
  } catch (error) {
    add("consultation_save", false, { error: shortError(error) });
    console.log(JSON.stringify(results, null, 2));
    return;
  }

  try {
    const reloaded = await rpc(client, "rpc_open_consultation", {
      p_requester_id: requesterId,
      p_appointment_id: appointmentId,
    });
    const savedPayload = reloaded?.consultation?.speciality_payload || {};
    const savedDiagnoses = toArray(reloaded?.diagnoses);

    expect(reloaded?.consultation?.id === consultationId, "Consultation id changed after reload");
    expect(reloaded?.consultation?.observations === observationsText, "Observation text mismatch");
    expect(reloaded?.consultation?.treatment_plan === treatmentPlan, "Treatment plan mismatch");
    expect(reloaded?.consultation?.follow_up === followUp, "Follow up mismatch");
    expect(reloaded?.consultation?.speciality_key === "general_medicine", "Workspace key mismatch");
    expect(hasAllValues(savedPayload?.symptoms_selected, selectedSymptoms), "Symptoms were not persisted", {
      actual: savedPayload?.symptoms_selected,
    });
    expect(
      hasAllValues(
        savedDiagnoses.map((item) => item.label || item.code),
        diagnosisLabels,
      ),
      "Diagnoses were not persisted",
      { actual: savedDiagnoses },
    );
    expect(String(savedPayload?.conclusion || "") === specialityPayload.conclusion, "Conclusion payload mismatch");
    expect(String(savedPayload?.doctor_note || "") === specialityPayload.doctor_note, "Custom observation payload mismatch");

    add("consultation_submodules_roundtrip", true, {
      symptomsCount: toArray(savedPayload?.symptoms_selected).length,
      diagnosesCount: savedDiagnoses.length,
    });
  } catch (error) {
    add("consultation_submodules_roundtrip", false, {
      error: shortError(error),
      details: error?.details || null,
    });
  }

  try {
    const createdPrescription = await rpc(client, "rpc_upsert_prescription", {
      p_requester_id: requesterId,
      p_consultation_id: consultationId,
      p_patient_id: patientId,
      p_template_name: "Consultation",
      p_signed_by: "Dr Test1",
      p_status: "draft",
      p_notes: `Prescription ${uniqueTag}`,
      p_medications: [
        {
          medicine_name: "Paracetamol",
          dose: "500 mg",
          frequency: "2x/day",
          duration: "5 days",
          instructions: "After meals",
        },
        {
          medicine_name: "Vitamin C",
          dose: "1 g",
          frequency: "1x/day",
          duration: "7 days",
          instructions: "Morning",
        },
      ],
    });
    prescriptionId = createdPrescription?.id || null;
    expect(!!prescriptionId, "Prescription was not created");
    add("ordonnance_create", true, {
      prescriptionId,
      status: createdPrescription?.status ?? null,
      medicationCount: toArray(createdPrescription?.medications).length,
    });
  } catch (error) {
    add("ordonnance_create", false, { error: shortError(error) });
  }

  try {
    expect(!!prescriptionId, "Missing prescription id for update");
    const updatedPrescription = await rpc(client, "rpc_upsert_prescription", {
      p_requester_id: requesterId,
      p_consultation_id: consultationId,
      p_patient_id: patientId,
      p_prescription_id: prescriptionId,
      p_template_name: "Consultation",
      p_signed_by: "Dr Test1",
      p_status: "signed",
      p_notes: `Prescription signed ${uniqueTag}`,
      p_medications: [
        {
          medicine_name: "Paracetamol",
          dose: "1 g",
          frequency: "3x/day",
          duration: "3 days",
          instructions: "After meals",
        },
      ],
    });
    expect(updatedPrescription?.status === "signed", "Prescription did not become signed", {
      status: updatedPrescription?.status,
    });
    add("ordonnance_sign", true, {
      status: updatedPrescription?.status ?? null,
      medicationCount: toArray(updatedPrescription?.medications).length,
    });
  } catch (error) {
    add("ordonnance_sign", false, { error: shortError(error) });
  }

  try {
    const prescriptions = await rpc(client, "rpc_get_prescriptions", {
      p_requester_id: requesterId,
      p_consultation_id: consultationId,
      p_patient_id: patientId,
      p_limit: 10,
    });
    const current = toArray(prescriptions).find((row) => row.id === prescriptionId);
    expect(!!current, "Saved prescription not returned in listing");
    expect(current.status === "signed", "Prescription listing status mismatch", { status: current.status });
    expect(toArray(current.medications).length === 1, "Prescription medication count mismatch", {
      medications: current.medications,
    });
    expect(
      String(current.medications?.[0]?.medicine_name || "") === "Paracetamol",
      "Prescription medication content mismatch",
    );
    add("ordonnance_roundtrip", true, {
      returnedCount: toArray(prescriptions).length,
      status: current.status,
    });
  } catch (error) {
    add("ordonnance_roundtrip", false, {
      error: shortError(error),
      details: error?.details || null,
    });
  }

  try {
    const closed = await rpc(client, "rpc_close_consultation", {
      p_requester_id: requesterId,
      p_consultation_id: consultationId,
    });
    expect(closed === true, "Consultation close did not return true", { closed });
    const details = await rpc(client, "rpc_get_appointment_details", {
      p_requester_id: requesterId,
      p_appointment_id: appointmentId,
    });
    expect(details?.status === "completed", "Appointment did not become completed", {
      status: details?.status,
    });
    const finalSession = await rpc(client, "rpc_open_consultation", {
      p_requester_id: requesterId,
      p_appointment_id: appointmentId,
    });
    expect(finalSession?.consultation?.status === "closed", "Consultation did not remain closed", {
      status: finalSession?.consultation?.status,
    });
    add("consultation_close_roundtrip", true, {
      appointmentStatus: details?.status ?? null,
      consultationStatus: finalSession?.consultation?.status ?? null,
    });
  } catch (error) {
    add("consultation_close_roundtrip", false, {
      error: shortError(error),
      details: error?.details || null,
    });
  }

  add("lettres_backend_note", true, {
    note: "Lettres tab is frontend-generated print/save text only; no Supabase persistence RPC exists to test live.",
  });

  console.log(JSON.stringify(results, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
